const heads = ['Название', 'Жанр', 'Год выхода', 'Страна', 'Тип', 'Бюджет']

const buildings = [
    ['Doom eternal', 'шутер', '2020', 'США', 'AAA', '314'],
    ['Left 4 Dead', 'шутер', '2009', 'США', 'AA', '11'],
    ['Battlefield: bad company', 'шутер', '2010', 'Швеция', 'AA', '20'],
    ['Singularity', 'шутер', '2010', 'США', 'AA', '30'],
    ['TimeShift', 'шутер', '2007', 'США', 'AA', '20'],
    ['Far Cry 3', 'шутер', '2012', 'Франция', 'AA', '30'],
    ['Metro 2033 redux', 'шутер', '2014', 'Украина', 'A', '10'],
    ['bulletstorm', 'шутер', '2011', 'Польша', 'AA', '20'],
    ['Payday 2', 'шутер', '2013', 'Швеция', 'A', '3'],
    ['Titanfall 2', 'шутер', '2016', 'США', 'AA', '40'],
    ['Elden Ring', 'Соулс-лайк', '2020', 'Япония', 'AAA', '160'],
    ['Lies of p', 'Соулс-лайк', '2023', 'Корея', 'AA', '30'],
    ['Lord of the Fallen', 'Соулс-лайк', '2023', 'США', 'AA', '40'],
    ['Sekiro: shadows die twice', 'Соулс-лайк', '2019', 'Япония', 'AA', '70'],
    ['Mortal Shell', 'Соулс-лайк', '2020', 'США', 'A', '5'],
    ['Bloodborne', 'Соулс-лайк', '2015', 'Япония', 'AA', '20'],
    ['Nioh 2', 'Соулс-лайк', '2020', 'Япония', 'AA', '40'],
    ['Code Vein', 'Соулс-лайк', '2019', 'Япония', 'AA', '20'],
    ['Blasphemous', 'Соулс-лайк', '2019', 'Испания', 'A', '1'],
    ['Wo Long', 'Соулс-лайк', '2023', 'Япония', 'AA', '30'],
    ['Resident Evil 7', 'survival horror', '2017', 'Япония', 'AA', '30'],
    ['Silent hill 2 remake', 'survival horror', '2024', 'Польша', 'AA', '50'],
    ['Resident Evil 4 remake', 'survival horror', '2023', 'Япония', 'AA', '25'],
    ['SOMA', 'survival horror', '2015', 'Швеция', 'A', '1'],
    ['Alien isolation', 'survival horror', '2014', 'Великобритания', 'AA', '30'],
    ['Alan wake 2', 'survival horror', '2023', 'Финляндия', 'AA', '70'],
    ['Control', 'survival horror', '2019', 'Финляндия', 'AA', '30'],
    ['Days Gone', 'survival horror', '2019', 'США', 'AAA', '150'],
    ['Dead space', 'survival horror', '2008', 'США', 'A', '4'],
    ['Dead space 2', 'survival horror', '2010', 'США', 'AA', '60'],
    ['Metal Gear Rising', 'Слэшер', '2013', 'Япония', 'AA', '25'],
    ['Bayonetta', 'Слэшер', '2009', 'Япония', 'AA', '20'],
    ['Devil May Cry 5', 'Слэшер', '2016', 'Япония', 'AA', '80'],
    ['Katana zero', 'Слэшер', '2019', 'США', 'A', '1'],
    ['Devil May Cry 4', 'Слэшер', '2008', 'Япония', 'AA', '40'],
    ['Devil May Cry 3', 'Слэшер', '2006', 'Япония', 'AA', '15'],
    ['Bayonetta 2', 'Слэшер', '2014', 'Япония', 'AA', '50'],
    ['God of War Ragnarok', 'Слэшер', '2022', 'США', 'AAA', '200'],
    ['Nier Automata', 'Слэшер', '2017', 'Япония', 'AA', '30'],
    ['Ghostrunner 2', 'Слэшер', '2023', 'Польша', 'A', '5'],
    ['Dead cells', 'Roguelike', '2018', 'Франция', 'A', '5'],
    ['Hades', 'Roguelike', '2018', 'США', 'A', '5'],
    ['Hades 2', 'Roguelike', '2024', 'США', 'AA', '20'],
    ['Darkest Dungeon', 'Roguelike', '2016', 'Канада', 'A', '1'],
    ['Durkest Dungeon 2', 'Roguelike', '2023', 'Канада', 'A', '5'],
    ['The binding of Isaac', 'Roguelike', '2011', 'США', 'A', '1'],
    ['Enter the Gungeon', 'Roguelike', '2017', 'США', 'A', '5'],
    ['Risk of Rain 2', 'Roguelike', '2013', 'Великобритания', 'A', '1'],
    ['Noita', 'Roguelike', '2019', 'Финляндия', 'A', '1'],
    ["Don't starve", 'Roguelike', '2013', 'Канада', 'A', '1']
]